import Head from 'next/head';
import Box from '@mui/joy/Box';

import { useState } from 'react';

import NavBar from './navbar';
import SideBar from './sidebar';

const Base = (props) => (
    <Box
      {...props}
      sx={[
        {
          bgcolor: 'background.appBody',
          display: 'grid',
          gridTemplateColumns: {
            xs: '1fr',
            sm: 'minmax(64px, 200px) minmax(450px, 1fr)',
            md: 'minmax(160px, 300px) minmax(300px, 500px) minmax(500px, 1fr)',
          },
          gridTemplateRows: '64px 1fr',
          minHeight: '100vh',
        },
        ...(Array.isArray(props.sx) ? props.sx : [props.sx]),
      ]}
    />
  );

const Content = (props) => {
  return (
  <Box sx={{ width: '100%'}} {...props} />
  );
};

const Page = ({ title = '~~~ Swimming ~~', children }) => {
  const sidebarState = useState(false);

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Base
                sx={{
                    height: '100vh',
                    overflow: 'hidden',
                }}
            >
                <NavBar sidebarState={sidebarState} />
                <Box
                  sx={{
                    display: 'flex',
                    gridColumn: '1 / -1',
                  }}
                >
                  <Content>
                    {children}
                  </Content>
                  <SideBar sidebarState={sidebarState} />
                </Box>
            </Base>
        </>
    );
};

export default Page;