import Head from 'next/head';
import Box from '@mui/joy/Box';

import { useState } from 'react';

import NavBar from './navbar';
import SideBar from './sidebar';
import Content from './content';

const Page = ({ title = '~~~ Swimming ~~', children }) => {
    const sidebarState = useState(false);

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Box
                sx={{
                    display: 'grid',
                    height: '100vh',
                    minHeight: '100vh',
                    overflow: 'hidden',
                    bgcolor: 'background.appBody',
                    gridTemplateRows: '64px 1fr',
                }}
            >
                <NavBar sidebarState={sidebarState} />
                <Box
                    sx={{
                        display: 'flex',
                        gridColumn: '1 / -1',
                    }}
                >
                    <Content>
                        {children}
                    </Content>
                    <SideBar sidebarState={sidebarState} />
                </Box>
            </Box>
        </>
    );
};

export default Page;