import Head from 'next/head';
import NavBar from './navbar';

const Page = ({ title = '🌊Mr 🐙 is swimming🌊', children }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <NavBar/>
            {children}
        </>
    );
};

export default Page;